name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1a

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Deploy to Elastic Beanstalk
        run: |
          eb init -r us-east-1 -p python-3.8 Flask-env
          eb deploy Flask-env
