name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
    - master
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Elastic Beanstalk CLI
        run: |
          pip install awsebcli --upgrade --user
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Initialize Elastic Beanstalk environment
        run: eb init -r us-east-1 -p python-3.11 Flask-env

      - name: Redeploy to Elastic Beanstalk
        run: eb deploy e-m92ivt53p8 --env Flask-env
